"""Build the end-to-end fixture scenes (generated by verify_end_to_end.py)."""
import os
import sys

import bpy

OUT = sys.argv[sys.argv.index("--") + 1] if "--" in sys.argv else None
if not OUT:
    raise SystemExit("usage: blender -b -P make_e2e_scenes.py -- <output dir>")
os.makedirs(OUT, exist_ok=True)


def build(path, *, cameras=1, obstacle=False, floor=True):
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.frame_start, scene.frame_end = 0, 80
    scene.render.fps = 24
    scene.render.resolution_x, scene.render.resolution_y = 320, 180
    scene.render.resolution_percentage = 100
    scene.render.engine = "BLENDER_WORKBENCH"

    if floor:
        bpy.ops.mesh.primitive_plane_add(size=30.0, location=(0.0, 0.0, 0.0))
        bpy.context.active_object.name = "Floor"
    # A back wall so forward dollies have something to approach.
    bpy.ops.mesh.primitive_plane_add(size=30.0, location=(-12.0, 0.0, 4.0),
                                     rotation=(0.0, 1.5707963, 0.0))
    bpy.context.active_object.name = "BackWall"
    if obstacle:
        bpy.ops.mesh.primitive_plane_add(size=10.0, location=(3.0, 0.0, 3.0),
                                         rotation=(0.0, 1.5707963, 0.0))
        bpy.context.active_object.name = "Obstacle"

    for index in range(max(1, cameras)):
        bpy.ops.object.camera_add(location=(0.0, index * 2.0, 1.6),
                                  rotation=(1.5707963, 0.0, -1.5707963))
        camera = bpy.context.active_object
        camera.name = "Camera" if index == 0 else "Camera_%02d" % (index + 1)
        camera.data.lens = 35.0
        camera.data.clip_start = 0.1
        camera.data.clip_end = 200.0
        if index == 0:
            scene.camera = camera
    scene.frame_set(0)
    bpy.ops.wm.save_as_mainfile(filepath=path, check_existing=False, compress=False)
    print("wrote", path)


build(os.path.join(OUT, "room001.blend"))
build(os.path.join(OUT, "room002.blend"), obstacle=True)
build(os.path.join(OUT, "multi_camera.blend"), cameras=3)
