"""End-to-end verification through the *command line* interfaces.

This is the acceptance test for the delivery: it shells out to Blender exactly
the way a user or a render farm would, using the real 80-template reference
document, and checks the documented artifacts appear.

    <blender> -b -P tests/verify_end_to_end.py

Exit code 0 means every stage worked.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
_PACKAGE_ROOT = os.path.dirname(_HERE)
_WORKSPACE = os.path.dirname(_PACKAGE_ROOT)
if _WORKSPACE not in sys.path:
    sys.path.insert(0, _WORKSPACE)
sys.path.insert(0, _HERE)
import _boot  # noqa: E402,F401  (the add-on folder may be called anything)

def _resolve_blender() -> str:
    """The Blender *executable*, not the Python interpreter.

    Under ``blender -P`` ``sys.executable`` is Blender's bundled ``python.exe``,
    which cannot run ``-b -P``; ``bpy.app.binary_path`` is the right one.
    """
    override = os.environ.get("MP_BLENDER")
    if override:
        return override
    try:
        import bpy  # type: ignore

        if bpy.app.binary_path:
            return bpy.app.binary_path
    except Exception:
        pass
    return sys.executable


BLENDER = _resolve_blender()
PACKAGE = _PACKAGE_ROOT
WORK = os.path.join(tempfile.gettempdir(), "motion_pipeline_e2e")
SCENES = os.path.join(WORK, "scenes")
GENERATED = os.path.join(WORK, "generated")
RENDERED = os.path.join(WORK, "rendered")
REFERENCE_TEMPLATES = os.path.join(
    r"E:\UE\DataGenScenes\Plugins\MetaHumanScenePipeline\Templates",
    "camera_motion_templates.json",
)

#: The dated project folder the generation step creates inside ``GENERATED``.
PROJECT = ""


def project_folder() -> str:
    """Newest ``blender_camera_*`` folder under ``GENERATED`` ("" when not there)."""
    if not os.path.isdir(GENERATED):
        return ""
    from blender_motion_pipeline.core.project import PROJECT_PREFIX

    found = sorted(
        os.path.join(GENERATED, name)
        for name in os.listdir(GENERATED)
        if name.startswith(PROJECT_PREFIX) and os.path.isdir(os.path.join(GENERATED, name))
    )
    return found[-1] if found else ""

STEPS: "list[tuple[str, bool, str]]" = []


def record(name: str, ok: bool, detail: str = "") -> None:
    STEPS.append((name, ok, detail))
    print(f"[{'ok  ' if ok else 'FAIL'}] {name}" + (f" -- {detail}" if detail else ""), flush=True)


def run_blender(script: str, args: "list[str]", *, blend: str = "", timeout: int = 1800):
    """Invoke Blender headlessly and return ``(exit_code, stdout, stderr)``."""
    command = [BLENDER, "-b"]
    if blend:
        command.append(blend)
    command += ["-P", script, "--"] + args
    print(f"  $ {' '.join(command[:4])} ... ({len(args)} arg(s))", flush=True)
    started = time.time()
    completed = subprocess.run(command, capture_output=True, text=True, timeout=timeout)
    elapsed = time.time() - started
    print(f"    exit={completed.returncode} in {elapsed:.1f}s", flush=True)
    if completed.returncode != 0:
        tail = (completed.stdout or "")[-3000:]
        print("    --- stdout tail ---\n" + tail, flush=True)
        print("    --- stderr tail ---\n" + (completed.stderr or "")[-2000:], flush=True)
    return completed.returncode, completed.stdout or "", completed.stderr or ""


def make_scene_script() -> str:
    """Write the fixture-builder script (also used by the E2E make step)."""
    path = os.path.join(_HERE, "make_e2e_scenes.py")
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(MAKE_SCENES_SOURCE)
    return path


MAKE_SCENES_SOURCE = '''"""Build the end-to-end fixture scenes (generated by verify_end_to_end.py)."""
import os
import sys

import bpy

OUT = sys.argv[sys.argv.index("--") + 1] if "--" in sys.argv else None
if not OUT:
    raise SystemExit("usage: blender -b -P make_e2e_scenes.py -- <output dir>")
os.makedirs(OUT, exist_ok=True)


def build(path, *, cameras=1, obstacle=False, floor=True):
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.frame_start, scene.frame_end = 0, 80
    scene.render.fps = 24
    scene.render.resolution_x, scene.render.resolution_y = 320, 180
    scene.render.resolution_percentage = 100
    scene.render.engine = "BLENDER_WORKBENCH"

    if floor:
        bpy.ops.mesh.primitive_plane_add(size=30.0, location=(0.0, 0.0, 0.0))
        bpy.context.active_object.name = "Floor"
    # A back wall so forward dollies have something to approach.
    bpy.ops.mesh.primitive_plane_add(size=30.0, location=(-12.0, 0.0, 4.0),
                                     rotation=(0.0, 1.5707963, 0.0))
    bpy.context.active_object.name = "BackWall"
    if obstacle:
        bpy.ops.mesh.primitive_plane_add(size=10.0, location=(3.0, 0.0, 3.0),
                                         rotation=(0.0, 1.5707963, 0.0))
        bpy.context.active_object.name = "Obstacle"

    for index in range(max(1, cameras)):
        bpy.ops.object.camera_add(location=(0.0, index * 2.0, 1.6),
                                  rotation=(1.5707963, 0.0, -1.5707963))
        camera = bpy.context.active_object
        camera.name = "Camera" if index == 0 else "Camera_%02d" % (index + 1)
        camera.data.lens = 35.0
        camera.data.clip_start = 0.1
        camera.data.clip_end = 200.0
        if index == 0:
            scene.camera = camera
    scene.frame_set(0)
    bpy.ops.wm.save_as_mainfile(filepath=path, check_existing=False, compress=False)
    print("wrote", path)


build(os.path.join(OUT, "room001.blend"))
build(os.path.join(OUT, "room002.blend"), obstacle=True)
build(os.path.join(OUT, "multi_camera.blend"), cameras=3)
'''


def step_make_scenes() -> str:
    script = make_scene_script()
    code, _out, _err = run_blender(script, [SCENES], timeout=600)
    blends = sorted(
        os.path.join(SCENES, name) for name in os.listdir(SCENES)
    ) if os.path.isdir(SCENES) else []
    record(
        "1. build fixture scenes",
        code == 0 and len(blends) == 3,
        f"{len(blends)} scene(s) in {SCENES}",
    )
    return "" if code == 0 else "scene build failed"


def step_dry_run() -> str:
    config_path = os.path.join(WORK, "config.json")
    from blender_motion_pipeline.config.defaults import default_config, save_config_file

    config = default_config()
    config.batch.output_root = GENERATED
    config.motion.template_path = REFERENCE_TEMPLATES
    config.motion.template_names = ["dolly_in_01_standard", "pan_right_01_standard",
                                    "fixed_01_standard", "zoom_in_03_strong"]
    config.search.candidate_count = 24
    config.search.azimuth_samples = 8
    config.search.elevation_samples = 3
    config.validation.sample_step = 5
    config.render.resolution_x = 320
    config.render.resolution_y = 180
    save_config_file(config_path, config)

    cli = os.path.join(PACKAGE, "motion_pipeline_cli.py")
    code, out, _err = run_blender(
        cli,
        ["--config", config_path, "--scene-dir", SCENES, "--dry-run", "--log-level", "WARNING"],
        timeout=900,
    )
    summarised = "would generate" in out
    record(
        "2. CLI dry-run reports the sequence matrix",
        code == 0 and summarised,
        next((line.strip() for line in out.splitlines() if "would generate" in line), ""),
    )
    return config_path if code == 0 else "dry run failed"


def step_generate(config_path: str) -> str:
    global PROJECT

    cli = os.path.join(PACKAGE, "motion_pipeline_cli.py")
    code, out, _err = run_blender(
        cli,
        ["--config", config_path, "--scene-dir", SCENES, "--log-level", "WARNING",
         "--report", os.path.join(WORK, "cli_report.json")],
        timeout=1800,
    )
    PROJECT = project_folder()
    sequences = []
    for current, _dirs, files in os.walk(os.path.join(PROJECT, "sequence")):
        if "sequence_config.json" in files:
            sequences.append(current)
    record(
        "3. CLI generated sequences (real 80-template document)",
        code == 0 and len(sequences) >= 3,
        f"{len(sequences)} sequence folder(s) in {PROJECT}",
    )
    return PROJECT if code == 0 else "generation failed"


def step_check_project(project: str) -> None:
    """The folder must be renderable on another machine as it stands."""
    problems = []
    for directory in ("sequence", "scene", "video"):
        if not os.path.isdir(os.path.join(project, directory)):
            problems.append(f"missing {directory}/")
    for name in ("project.json", "RENDER_README.md"):
        if not os.path.isfile(os.path.join(project, name)):
            problems.append(f"missing {name}")
    # Slim layout: the folder is data only, the renderer comes from the image.
    for name in ("render_sequences.py", "pack_textures.py",
                 "render_project.bat", "render_project.sh",
                 "blender_camera_motion_pipeline"):
        if os.path.exists(os.path.join(project, name)):
            problems.append(f"{name} must not be shipped inside the project folder")
    copies = sorted(os.listdir(os.path.join(project, "scene"))) if os.path.isdir(
        os.path.join(project, "scene")) else []
    if len(copies) != 3:
        problems.append(f"expected 3 scene copies, found {len(copies)}: {copies}")
    # Every sequence must record the *copy* it was generated from, in absolute and
    # project-relative form.
    checked = 0
    for current, _dirs, files in os.walk(os.path.join(project, "sequence")):
        if "sequence_config.json" not in files:
            continue
        checked += 1
        with open(os.path.join(current, "sequence_config.json"), encoding="utf-8") as handle:
            payload = json.load(handle)
        sequence = payload.get("sequence") or {}
        recorded = sequence.get("source_blend") or ""
        relative = sequence.get("source_scene_rel") or ""
        if os.path.normcase(os.path.dirname(recorded)) != os.path.normcase(
            os.path.join(project, "scene")
        ):
            problems.append(f"{current}: source_blend is not the project's scene copy: {recorded}")
        if not relative or not os.path.isfile(os.path.join(project, relative)):
            problems.append(f"{current}: source_scene_rel does not resolve inside the project: {relative}")
    record(
        "4. the project folder is data only and self-describing (sequence/ + scene/ + video/)",
        not problems and checked >= 3 and len(copies) == 3,
        f"{checked} sequence(s), {len(copies)} scene copy/copies"
        + (f"; {problems[0]}" if problems else ""),
    )
    for problem in problems[:5]:
        print("     !", problem)


def step_check_artifacts(root: str) -> str:
    problems = []
    checked = 0
    for current, _dirs, files in os.walk(root):
        if "sequence_config.json" not in files:
            continue
        checked += 1
        name = os.path.basename(current)
        # Animation-only sequences carry no scene copy: the .blend they replay onto
        # is the one shipped in the project's scene/ folder.
        for expected in (
            "sequence_config.json",
            f"{name}.json",
            f"{name}_camera.txt",
            "generation_log.txt",
            "validation_report.json",
        ):
            if expected not in files:
                problems.append(f"{current}: missing {expected}")
        # The sidecar JSON must carry the reference-compatible keys.
        sidecar = os.path.join(current, f"{name}.json")
        if os.path.isfile(sidecar):
            with open(sidecar, "r", encoding="utf-8") as handle:
                payload = json.load(handle)
            for key in ("level_name", "sequence_name", "video_id", "video_path",
                        "frame_count", "camera_trajectory", "text_prompt"):
                if key not in payload:
                    problems.append(f"{sidecar}: missing key {key!r}")
        # The trajectory TXT must have the reference header and one row per frame.
        trajectory = os.path.join(current, f"{name}_camera.txt")
        if os.path.isfile(trajectory):
            with open(trajectory, "r", encoding="utf-8") as handle:
                lines = [line for line in handle.read().splitlines() if not line.startswith("#")]
            if not lines or not lines[0].startswith("frame focal_length d1 d2 d3 d4 d5"):
                problems.append(f"{trajectory}: wrong header")
            elif len(lines) - 1 != 81:
                problems.append(f"{trajectory}: {len(lines) - 1} rows, expected 81")
    record(
        "5. generated artifacts match the documented layout",
        not problems and checked >= 3,
        f"{checked} sequence(s) checked" + (f"; {problems[0]}" if problems else ""),
    )
    for problem in problems[:5]:
        print("     !", problem)
    return root if not problems else "artifact problems"


def step_render() -> str:
    """Render the project with *its own* copy of the renderer.

    Nothing about the developer's machine is allowed to matter here: the script is
    the one shipped inside the project folder, it imports the package copied beside
    it, it discovers the scenes through the recorded relative path, and it writes
    into the project's own ``video/`` folder.
    """
    script = os.path.join(PROJECT, "render_sequences.py")
    code, out, _err = run_blender(
        script,
        ["--input-root", os.path.join(PROJECT, "sequence"),
         "--output-root", os.path.join(PROJECT, "video"),
         "--resolution-x", "320",
         "--resolution-y", "180",
         "--engine", "BLENDER_WORKBENCH",
         "--log-level", "WARNING"],
        timeout=1800,
    )
    videos = []
    for current, _dirs, files in os.walk(os.path.join(PROJECT, "video")):
        videos.extend(
            os.path.join(current, name) for name in files if name.endswith(".mp4")
        )
    record(
        "6. headless render produced videos into the project's video/ folder",
        code == 0 and len(videos) >= 3,
        f"{len(videos)} video(s) in {os.path.join(PROJECT, 'video')}",
    )
    return os.path.join(PROJECT, "video") if code == 0 else "render failed"


def step_render_artifacts(root: str) -> str:
    problems = []
    triples = 0
    for current, _dirs, files in os.walk(root):
        videos = [name for name in files if name.endswith(".mp4")]
        if not videos:
            continue
        triples += 1
        for video in videos:
            stem = os.path.splitext(video)[0]
            for sibling in (f"{stem}.json", f"{stem}_camera.txt"):
                if sibling not in files:
                    problems.append(f"{current}: missing {sibling}")
            if os.path.getsize(os.path.join(current, video)) <= 0:
                problems.append(f"{current}/{video}: zero bytes")
            # Validate the video with ffprobe when it is available.
            sidecar = os.path.join(current, f"{stem}.json")
            if os.path.isfile(sidecar):
                with open(sidecar, "r", encoding="utf-8") as handle:
                    payload = json.load(handle)
                if payload.get("status") != "rendered":
                    problems.append(f"{sidecar}: status {payload.get('status')!r}")
                if not payload.get("camera_trajectory"):
                    problems.append(f"{sidecar}: empty camera_trajectory")
    record(
        "7. every video has its JSON + trajectory TXT beside it",
        not problems and triples >= 3,
        f"{triples} sequence output folder(s)" + (f"; {problems[0]}" if problems else ""),
    )
    for problem in problems[:5]:
        print("     !", problem)
    return root if not problems else "render artifact problems"


def step_ffprobe(root: str) -> None:
    ffprobe = shutil.which("ffprobe")
    if not ffprobe:
        record("8. video streams decode (ffprobe)", True, "ffprobe not on PATH; skipped")
        return
    videos = []
    for current, _dirs, files in os.walk(root):
        videos.extend(os.path.join(current, n) for n in files if n.endswith(".mp4"))
    problems = []
    for video in sorted(videos)[:3]:
        completed = subprocess.run(
            [ffprobe, "-v", "error", "-show_entries",
             "stream=codec_name,width,height,nb_frames", "-of", "json", video],
            capture_output=True, text=True,
        )
        if completed.returncode != 0:
            problems.append(f"{video}: ffprobe failed")
            continue
        payload = json.loads(completed.stdout or "{}")
        streams = payload.get("streams") or []
        if not streams or streams[0].get("codec_name") != "h264":
            problems.append(f"{video}: unexpected streams {streams}")
        elif int(streams[0].get("nb_frames") or 0) != 81:
            problems.append(f"{video}: {streams[0].get('nb_frames')} frames, expected 81")
    record(
        "8. video streams decode with the expected frame count",
        not problems,
        f"{len(videos)} video(s) probed" + (f"; {problems[0]}" if problems else ""),
    )


def step_resume() -> None:
    script = os.path.join(PROJECT, "render_sequences.py")
    code, out, _err = run_blender(
        script,
        ["--input-root", os.path.join(PROJECT, "sequence"),
         "--output-root", os.path.join(PROJECT, "video"),
         "--log-level", "INFO"],
        timeout=900,
    )
    # A fully rendered tree must be a success, and the renderer must say so.
    record(
        "9. re-running the renderer skips finished sequences",
        code == 0 and "already have a video" in out,
        next(
            (line.strip() for line in out.splitlines() if "already have a video" in line),
            "",
        ),
    )


def step_list() -> None:
    script = os.path.join(PROJECT, "render_sequences.py")
    code, out, _err = run_blender(
        script,
        ["--input-root", os.path.join(PROJECT, "sequence"),
         "--output-root", os.path.join(PROJECT, "video"), "--list",
         "--log-level", "ERROR"],
        timeout=600,
    )
    record(
        "10. --list enumerates sequences and their state",
        code == 0 and "sequence(s):" in out and "rendered" in out,
        next((line.strip() for line in out.splitlines() if "sequence(s)" in line), ""),
    )


def main() -> int:
    print("=" * 74)
    print("Motion Pipeline end-to-end verification")
    print(f"  blender : {BLENDER}")
    print(f"  work    : {WORK}")
    print(f"  templates: {REFERENCE_TEMPLATES}")
    print("=" * 74)
    if not os.path.isfile(REFERENCE_TEMPLATES):
        print(f"reference template document not found: {REFERENCE_TEMPLATES}")
        return 1
    shutil.rmtree(WORK, ignore_errors=True)
    os.makedirs(WORK, exist_ok=True)

    failure = step_make_scenes()
    if not failure:
        config_path = step_dry_run()
        if isinstance(config_path, str) and os.path.isfile(config_path):
            root = step_generate(config_path)
            if isinstance(root, str) and os.path.isdir(root):
                print(f"  project : {root}")
                step_check_project(root)
                step_check_artifacts(os.path.join(root, "sequence"))
                rendered = step_render()
                if isinstance(rendered, str) and os.path.isdir(rendered):
                    step_render_artifacts(rendered)
                    step_ffprobe(rendered)
                    step_resume()
                    step_list()
                else:
                    record("6-10. render stages", False, str(rendered))
            else:
                record("4-10. generation stages", False, str(root))
        else:
            record("3-10. generation stages", False, str(config_path))
    else:
        record("2-10. pipeline stages", False, failure)

    print("\n" + "=" * 74)
    passed = sum(1 for _n, ok, _d in STEPS if ok)
    for name, ok, detail in STEPS:
        print(f"  [{'ok  ' if ok else 'FAIL'}] {name}" + (f" -- {detail}" if detail else ""))
    print(f"\n{passed}/{len(STEPS)} stage(s) passed")
    print("END-TO-END VERIFICATION PASSED" if passed == len(STEPS) else "END-TO-END VERIFICATION FAILED")
    print("=" * 74)
    if os.environ.get("MP_KEEP_E2E"):
        print(f"artifacts kept in {WORK}")
    else:
        shutil.rmtree(WORK, ignore_errors=True)
    return 0 if passed == len(STEPS) else 1


if __name__ == "__main__":
    sys.exit(main())
